return{
   "ERLC_Patched",
   "Arsenal_Unpatched",
   "JailBreak_Unpatched",
   "PrisonLife_Unpatched",
   "VehicleSimulator_Unpatched",
   "TappingSimulator_Unpatched",
   "MurderMystery_Unpatched"
}
